- packages/balancer-gql/src/gql/__generated__/arbitrum.ts
- packages/balancer-gql/src/gql/__generated__/goerli.ts
- packages/balancer-gql/src/gql/__generated__/mainnet.ts
- packages/balancer-gql/src/gql/__generated__/polygon.ts
- packages/balancer-gql/src/queries/pools.ts
- packages/next-app/src/app/metadata/(components)/SearchPoolForm.tsx
- packages/next-app/src/app/metadata/[network]/pool/[poolId]/(components)/PoolMetadataForm.tsx
- packages/next-app/src/app/metadata/layout.tsx
- packages/next-app/src/components/Header.tsx
- packages/next-app/src/lib/gql.ts
[linear issue](https://linear.app/bleu-llc/issue/BAL-134/select-pool-from-left-side-if-user-connected-or-search)
connected wallet
disconnected wallet
pool not found
> [Pool Metadata] creates search pool button and form

- packages/next-app/src/app/internalmanager/(components)/BatchWithdrawButton.tsx
- packages/next-app/src/app/internalmanager/[network]/page.tsx
- packages/next-app/src/app/stableswapsimulator/(components)/CustomDataForm.tsx
- packages/next-app/src/app/stableswapsimulator/(components)/InitialDataForm.tsx
- packages/next-app/src/app/stableswapsimulator/(components)/InitialEmptyDataForm.tsx
- packages/next-app/src/app/stableswapsimulator/(components)/Menu.tsx
- packages/next-app/src/components/SearchPoolForm.tsx
- packages/next-app/src/contexts/StableSwapContext.tsx
- packages/next-app/src/utils/formatNumber.ts
- packages/schema/index.ts
This PR solves the following feedback:
- Make the "Import pool parameters" larger/more obvious
- Load the app with a pool like wstETH/WETH already shown. It's the largest
- Can let users enter 4 for 4%  for the swap fee on frontend but calcs remain the same.
> [Stable Swap] Balancer feedback

- apps/balancer-tools/src/app/internalmanager/layout.tsx
- apps/balancer-tools/src/contexts/networks.tsx
- apps/balancer-tools/src/lib/gql.ts
- packages/gql/codegen.ts
This PR:
- adds Polygon
- fix Optimism url check on `getNetwork`
- remove sepolia from networks, because viem is not recognizing successful transactions
- remove `Subgraph.BalancerInternalManager` since `Subgraph.BalancerPools` now has `tokenInfo` on `userInternalBalances` query
Tested networks - Show token table:
- Ethereum -> Ok;
- Goerli -> Ok;
- Sepolia -> Ok;
- Polygon -> Ok;
- Polygon zkevm -> Ok;
- Gnosis -> Ok;
- Arbitrum -> Ok;
- Optimism -> Ok;
Tested networks - Transactions:
- Ethereum -> Ok;
- Goerli -> Ok;
- Sepolia -> Failed. The transaction occurs successfully, but viem doesn't find the transaction hash, invoking an error toast, when actually the transaction goes fine
> [Internal Manager] Add polygon , fix Optimism and remove Sepolia from networks

- apps/balancer-tools/src/app/poolsimulator/(components)/PoolTypeChangeConfirmation.tsx
- packages/math-poolsimulator/src/gyro2/index.ts
- packages/math-poolsimulator/src/gyroE/index.ts
- packages/math-poolsimulator/src/metastable/index.ts
We noticed on #188 that `_spotPriceAfterSwapExactTokenInForTokenOut(poolPairData, bnum(0))` might have the same result as our ` _spotPrice()`. 
We tested, both on test and on dev, and the results were the same. Therefore, this a PR that uses directly `_spotPriceAfterSwapExactTokenInForTokenOut()` from SOR to define ` _spotPrice()`.
This PR also fix the outline of `PoolTypeChangeConfirmation` buttons
> [Pool Simulator] Refactor Spot Price

- apps/balancer-tools/src/app/poolsimulator/(components)/AnalysisPage.tsx
- apps/balancer-tools/src/app/poolsimulator/(components)/Menu.tsx
- apps/balancer-tools/src/app/poolsimulator/(components)/SwapCurve.tsx
- apps/balancer-tools/src/app/poolsimulator/(utils)/index.ts
- apps/balancer-tools/src/contexts/PoolSimulatorContext.tsx
- packages/math-poolsimulator/src/fx/fixtures/data.json
- packages/math-poolsimulator/src/fx/index.test.ts
- packages/math-poolsimulator/src/fx/index.ts
- packages/math-poolsimulator/src/types.ts
This PR:
- Add the first version of spot price function for FX pools;
- Enable FX analysis without depth cost chart and with issues on tokens with different prices (e.g. EURS - USDC)
- Fix issue with graph scale on Swap Curve for FX pool.
- Enable 0 of swap fee.
> [Pool Simulator] Implement FX Math Pt.1

- apps/balancer-tools/src/__tests__/utils/calculateCurvePoints.test.tsx
- apps/balancer-tools/src/app/poolsimulator/(components)/AnalysisPage.tsx
- apps/balancer-tools/src/app/poolsimulator/(components)/Curves/ImpactCurve.tsx
- apps/balancer-tools/src/app/poolsimulator/(components)/Curves/SwapCurve.tsx
- apps/balancer-tools/src/app/poolsimulator/(components)/Curves/getBetaLimits.test.ts
- apps/balancer-tools/src/app/poolsimulator/(components)/Curves/getBetaLimits.ts
- apps/balancer-tools/src/app/poolsimulator/(utils)/index.ts
- apps/balancer-tools/src/app/poolsimulator/(workers)/impact-curve-calculation.ts
This PR:
- Adds the beta region on the price impact curve;
- Refactor Swap curve beta region functions;
As shown in the figure above, our beta region limits may not be accurate. This [issue](https://linear.app/bleu-llc/issue/BAL-663/beta-region-limit-calculation) will refer to this.
> [Pool Simulator] Add beta region limit on price impact curve

- apps/balancer-tools/src/app/apr/(utils)/calculatePoolStats.ts
- apps/balancer-tools/src/app/apr/api/route.ts
- apps/balancer-tools/src/app/apr/pool/(components)/HistoricalAPRChart.tsx
- apps/balancer-tools/src/app/apr/pool/(components)/HistoricalAPRPlot.tsx
- apps/balancer-tools/src/app/apr/pool/(components)/PoolOverviewCards.tsx
- apps/balancer-tools/src/app/apr/round/(components)/PoolListTable.tsx
- apps/balancer-tools/src/app/apr/round/(components)/TopPoolsChart.tsx
this PR refactors the API return on APR
previously: 
```
apr: number
```
now: 
```
apr: {
total: number;
breakdown: {
veBAL: number;
};
};
```
- for round views I'm considering APR total, which rn is the same as veBAL APR
> [APR] Refactor API tor return different APR types

- apps/balancer-tools/src/app/apr/(utils)/calculatePoolStats.ts
- apps/balancer-tools/src/app/apr/api/route.ts
This PR just exposes feeDiff as collectedFeesUSD to be shown on future chart on https://linear.app/bleu-llc/issue/BAL-712/add-tabs-with-historical-volume-tvl-collected-fees
Example of possible chart:
> [APR] expose collectedFeesUSD to API

- apps/balancer-tools/src/app/apr/pool/(components)/HistoricalAPRPlot.tsx
- apps/balancer-tools/src/app/apr/pool/(components)/PoolTokens.tsx
- apps/balancer-tools/src/app/apr/pool/(components)/PoolTokensTable.tsx
- apps/balancer-tools/src/app/apr/round/(components)/MoreFiltersButton.tsx
- apps/balancer-tools/src/app/apr/round/(components)/PoolListTable.tsx
- apps/balancer-tools/src/app/apr/round/(components)/TopPoolsChart.tsx
- apps/balancer-tools/src/components/Plot.tsx
- Added table title
- Altered table tooltip
- If table start with <10 pools it will show "All pools have been loaded" instead of "load more"
- Historical APR now should only show integer
- Redirect with default sorting if not on searchParams
- Load more not using selected filters
- Tokens had the same URL
Title Tooltip: All values are calculated at the end of the round
APR Tooltip: The value displayed is the min APR
> [APR] Minor UI fixes

- apps/balancer-tools/src/app/apr/(utils)/calculatePoolStats.ts
- apps/balancer-tools/src/app/apr/(utils)/getBALPriceByRound.ts
This shouldn't change anything majorly, just a refactor se we use average Bal price instead of one point at the end of the round
> [APR] use avg of vebal price instead of only one point on apr calc

- apps/balancer-tools/src/app/poolsimulator/(components)/AnalysisPage.tsx
- apps/balancer-tools/src/app/poolsimulator/(components)/Curves/ImpactCurve.tsx
- apps/balancer-tools/src/app/poolsimulator/(components)/Curves/SwapCurve.tsx
- apps/balancer-tools/src/app/poolsimulator/(components)/DepthCost.tsx
- apps/balancer-tools/src/app/poolsimulator/(components)/Menu.tsx
- apps/balancer-tools/src/app/poolsimulator/(utils)/getBetaLimits.test.ts
- apps/balancer-tools/src/app/poolsimulator/(utils)/getBetaLimits.ts
- apps/balancer-tools/src/app/poolsimulator/(workers)/swap-curve-calculation.ts
- apps/balancer-tools/src/contexts/PoolSimulatorContext.tsx
This PR:
- Refactor swap curve points calculations to AnalysisPage component;
- Refactor `analysisToken` to `initialAnalysisToken` and `customAnalysisToken` to avoid get this data with `findTokenBySymbol` function multiple times on the app;
- Use beta limits points (from swap curve) on Depth Cost Chart
- Add warning on the depth cost chart in case on pool already outside of the beta region.
> [Pool Simulator] Add depth cost points for fx pool based on beta limits

- apps/balancer-tools/src/app/apr/(utils)/tokenYield.ts
- apps/balancer-tools/src/app/apr/(utils)/vunerabilityAffectedPool.ts
This PR returns APR as 0 for bb-tokens affected by the vulnerability after 22th Aug.
It will return values prior to 22th Aug, but they seem to be too small
> [APR] Handle bb tokens on yield apr

- apps/balancer-tools/src/app/apr/(utils)/calculatePoolStats.ts
Fixes days without tvl, following Fabio's recommendation on [BAL-872](https://linear.app/bleu-llc/issue/BAL-872/handle-days-were-snapshot-does-not-exist#comment-be6f5eac)
[On Prod](https://tools.balancer.blue/apr/pool/ethereum/0x1a44e35d5451e0b78621a1b3e7a53dfaa306b1d000000000000000000000051b?startAt=09-14-2023&endAt=09-22-2023)
With the fix
> [APR] Add retry clause when fetching tvl/volume

- apps/balancer-tools/src/app/apr/(utils)/getFilteredApiUrl.ts
- apps/balancer-tools/src/app/apr/api/(utils)/computeAverages.ts
- apps/balancer-tools/src/app/apr/api/route.ts
- apps/balancer-tools/src/app/apr/page.tsx
- apps/balancer-tools/src/app/apr/pool/(components)/HistoricalCharts/index.tsx
- apps/balancer-tools/src/app/apr/pool/(components)/PoolOverviewCards.tsx
- apps/balancer-tools/src/app/apr/round/(components)/PoolListTable.tsx
This is working for one pool, but not for home date range
http://localhost:3000/apr/pool/ethereum/0x1e19cf2d73a72ef1332c882f20534b6519be0276000200000000000000000112?startAt=09-18-2023&endAt=09-21-2023
> [APR] Remove general avg from api

- apps/balancer-tools/src/app/apr/(components)/HeaderEndButton.tsx
- apps/balancer-tools/src/app/poolsimulator/(components)/SearchPoolFormDialog.tsx
- apps/balancer-tools/src/components/SearchPoolForm/index.tsx
Preview link: https://tools-monorepo-2i09av0rl-bleu-fi.vercel.app/
Preview link for pool simulator: https://tools-monorepo-2i09av0rl-bleu-fi.vercel.app/poolsimulator
This PR:
- adds gqlAdditionalVariable to SearchPoolForm
- Refactor Pool simulator SearchPoolForm to get pools by type using gqlAdditionalVariable
- on APR gets only pools that have the TVL greater then 5k
> [APR] Add additional arg to SearchPoolForm to filter GQL

- apps/balancer-tools/src/app/apr/api/(utils)/computeAverages.ts
- apps/balancer-tools/src/data/pools-without-gauge.json
Before it wouldn't average value if it was a nested Obj, ex:
``` 
[<day>]: [
{
"poolId": "0x1ee442b5326009bb18f2f472d3e0061513d1a0ff000200000000000000000464",
"apr": {
"total": 15.743566851554217,
"breakdown": {
"veBAL": 9.326595933579101
}
}
}],
[<day 2>]: [
{
"poolId": "0x1ee442b5326009bb18f2f472d3e0061513d1a0ff000200000000000000000464",
"apr": {
"total": 15.743566851554217,
"breakdown": {
"veBAL": 9.326595933579101
}
}
},
]
```
It wouldn't iterate over APR's values, so would end up adding
> [APR] Fix for not averaging nested objects

- apps/balancer-tools/src/lib/utils.ts
Before it would return an array, if no other value was found
> [APR] Refactor trimTrailingValues to remove all valueToTrim values

- apps/balancer-tools/src/app/apr/pool/(components)/HistoricalCharts/HistoricalChart.tsx
- apps/balancer-tools/src/app/apr/pool/(components)/HistoricalCharts/HistoricalData/formatSwapFeeChartData.tsx
- apps/balancer-tools/src/app/apr/pool/(components)/HistoricalCharts/HistoricalData/formatTvlChartData.tsx
- apps/balancer-tools/src/app/apr/pool/(components)/HistoricalCharts/HistoricalData/formatVolumeChartData.tsx
This PR:
- changes bar opacity
- moves APR traces to be always on the front
https://www.loom.com/share/39574ea16bc2460083ae9a6f9b7ab6e6?sid=a330bead-d596-40b9-a4d8-e21b816708ac
> [APR] Historical Chart UI improvements

- apps/cow-tools/src/app/milkman/(components)/TokenSelect.tsx
- apps/cow-tools/src/app/milkman/(components)/TransactionProgressBar.tsx
- apps/cow-tools/src/components/RootLayout.tsx
- apps/cow-tools/src/utils/cowTokenList.ts
https://www.loom.com/share/d7e0527a01fc477a860804ea67e73dca?sid=e040a84a-2b72-46da-b15e-94b5dc438c1f
> Add cow swap token list on token select

- apps/cow-amm-deployer/src/app/[userId]/amms/[id]/(components)/DisableAmmButton.tsx
- apps/cow-amm-deployer/src/app/[userId]/amms/[id]/(components)/EditAMMForm.tsx
- apps/cow-amm-deployer/src/components/DepositForm.tsx
- apps/cow-amm-deployer/src/components/Dialog.tsx
- apps/cow-amm-deployer/src/components/WithdrawForm.tsx
This PR:
- Add dialog asking if the user wants to remove all amm liquidity on disable it.
- Add buttons with common withdraw pct.
- Fix MAX withdraw rounding
> Add option to stop and remove all liquidity in one tx and improve withdraw UX
