bleu/monorepo

packages/contracts/src/PoolMetadataRegistry.sol, packages/contracts/test/PoolMetadataRegistry.t.sol
[linear issue](https://linear.app/bleu-llc/issue/BAL-85/check-if-the-caller-is-the-owner)
=> PoolMetadataRegistry -> Check if the caller is the owner before set the PoolMetadata

README.md, packages/contracts/.env.template, packages/contracts/README.md, remappings.txt
[Linear issue](https://linear.app/bleu-llc/issue/BAL-72/create-readme-and-ensure-code-is-documented)
=> Update readme files with the necessary information to run the project 

packages/next-app/src/components/OwnedPool.tsx
Hi @devjoaov 
I left some suggestions:
- we can use more HStack and VStack rather than Stack. 
- for a sake of simplification, we can trust the default values.
Here we have the same result:
=> OwnedPool (Chakra) suggested refactor

.prettierignore, packages/subgraph/manifest.template.yaml, packages/subgraph/package.json, packages/subgraph/schema.graphql, packages/subgraph/src/helpers/index.ts, packages/subgraph/src/mappings/poolMetadataRegistry.ts
[Linear BAL-36](https://linear.app/bleu-llc/issue/BAL-36/create-mapping-for-handling-metadata-updates-events)
=> Create pool metadata updates handler

packages/next-app/src/app/pool/[poolId]/MetadataAttribute.tsx, packages/next-app/src/components/ImageDialog.tsx, packages/next-app/src/components/PoolMetadataForm.tsx, packages/next-app/src/components/PoolMetadataFormModal.tsx, packages/next-app/src/components/index.ts
[linear issue](https://linear.app/bleu-llc/issue/BAL-100/implement-pool-metadata-modal-form-component)
rendered component:
=> Create pool metadata modal form

packages/next-app/package.json, packages/next-app/src/app/RootLayout.tsx, packages/next-app/src/app/pool/[poolId]/MetadataAttribute.tsx, packages/next-app/src/components/PoolMetadataFormModal.tsx, packages/next-app/src/contexts/PoolMetadataContext.tsx, pnpm-lock.yaml
[linear issue](https://linear.app/bleu-llc/issue/BAL-104/register-new-row-when-user-clicks-save-item-in-modal-form)
=> Register new attribute when user clicks save / edit an attribute

packages/next-app/src/app/pool/[poolId]/(components)/PoolMetadataForm.tsx, packages/next-app/src/components/Select.tsx
- disable key and type editing for existing keys
=> disable editing typename and key in added metadata

packages/contracts/package.json, packages/contracts/src/PoolMetadataAuthorization.sol, packages/contracts/src/PoolMetadataRegistry.sol, packages/contracts/test/PoolMetadataRegistry.t.sol
fixes [BAL-71](https://linear.app/bleu-llc/issue/BAL-71/create-function-to-check-whether-the-dao-owns-given-pool)
=> Create function to check whether the DAO owns given pool

packages/next-app/src/app/metadata/(components)/RootLayout.tsx, packages/next-app/src/lib/gql.ts, packages/next-app/src/lib/poolMetadataGql.ts, packages/next-app/src/wagmi/generated.ts, packages/pool-metadata-gql/codegen.ts, packages/pool-metadata-gql/src/gql/__generated__/arbitrum.ts, packages/pool-metadata-gql/src/gql/__generated__/mainnet.ts, packages/pool-metadata-gql/src/gql/__generated__/polygon.ts
Closes [BAL-63](https://linear.app/bleu-llc/issue/BAL-63/list-pools-owned-by-the-dao-when-a-signer-connects)
https://www.loom.com/share/f8208b4fb9f54217998b1573cb2e1083
=> Show DAO's pool list using Multisig addresses

packages/next-app/src/app/metadata/(components)/RootLayout.tsx, packages/next-app/src/lib/gql.ts, packages/next-app/src/utils/fetcher.ts
[linear issue](https://linear.app/bleu-llc/issue/BAL-156/pool-list-is-persisting-when-switching-networks)
[loom video](https://www.loom.com/share/bbf3a7ff9b4a41debd520a6c6ba9e3ab)
=> [Pool Metadata]: Do not persist pools data when switching networks

packages/next-app/src/app/metadata/layout.tsx, packages/next-app/src/components/Footer.tsx, packages/schema/index.ts
=> [Pool Metadata] create footer component

packages/next-app/src/app/metadata/[network]/pool/[poolId]/(components)/MetadataAttributesTable.tsx, packages/next-app/src/contexts/PoolMetadataContext.tsx
[linear issue](https://linear.app/bleu-llc/issue/BAL-183/create-remove-attribute-button)
https://www.loom.com/share/1418f112c2d94ee8901b4d090046ba05
=> [Pool Metadata] add "remove button" to metadata attributes table

packages/next-app/src/app/metadata/[network]/pool/[poolId]/(components)/MetadataAttributesTable/index.tsx, pnpm-lock.yaml
[linear issue](https://linear.app/bleu-llc/issue/BAL-186/truncate-texts-on-metadata-attributes-table)
=> Truncate texts on metadata attributes table

packages/next-app/src/app/metadata/[network]/pool/[poolId]/(components)/MetadataAttributesTable/Actions.tsx, packages/next-app/src/app/metadata/[network]/pool/[poolId]/(components)/MetadataAttributesTable/PredefinedMetadataModal.tsx, packages/next-app/src/app/metadata/[network]/pool/[poolId]/(components)/MetadataAttributesTable/index.tsx, packages/next-app/src/components/Checkbox.tsx, packages/next-app/src/contexts/PoolMetadataContext.tsx, packages/next-app/tailwind.config.js
[linear issue](https://linear.app/bleu-llc/issue/BAL-269/minor-refactor-buttons-and-colors)
=> Refactor buttons and colors

packages/gql/codegen.ts, packages/next-app/src/app/internalmanager/page.tsx, packages/next-app/src/hooks/useTransaction.ts, packages/shared/index.ts
This PR has the goal to reduce duplicated code between useTransactionMetadata and useInternalBalancesTransactions
=> [Internal Balances] create useInternalBalancesTransaction

packages/gql/codegen.ts, packages/next-app/src/app/internalmanager/(components)/InternalManagerProvider.tsx, packages/next-app/src/app/internalmanager/page.tsx, packages/next-app/src/components/RootLayout.tsx, packages/next-app/src/wagmi/client.ts
This PR adds mainnet support to internal manager app
=> [Internal Manager] Connection to mainnet

packages/gql/src/balancer-internal-manager/internalBalances.ts, packages/next-app/src/app/internalmanager/(components)/TokenTable.tsx, packages/next-app/src/app/internalmanager/[network]/[operationKind]/[tokenAddress]/page.tsx, packages/next-app/src/app/metadata/(components)/OwnedPoolsSidebarItems.tsx, packages/next-app/src/contexts/InternalManagerContext.tsx, packages/next-app/src/hooks/useTransaction.ts, packages/next-app/src/utils/fetcher.ts
https://www.loom.com/share/d263b587408944b3b09b88eff4a6453e
=> [Balancer Tools] refetch gql request when chain or user changes

packages/next-app/src/app/layout.tsx
Closes BAL-357
https://www.loom.com/share/0f44de0794c44278a3c967420cea1643
=> change body background to match footer and header

packages/next-app/package.json, packages/next-app/src/app/_serverActions.ts, packages/next-app/src/app/internalmanager/(components)/TokenSelect.tsx, packages/next-app/src/app/internalmanager/[network]/[operationKind]/[tokenAddress]/page.tsx, packages/next-app/src/contexts/InternalManagerContext.tsx, packages/next-app/tailwind.config.js, pnpm-lock.yaml
[Linear Issue](https://linear.app/bleu-llc/issue/BAL-323/fetch-balances-on-chain-for-tokens-from-balancer-tokenlists)
https://www.loom.com/share/9d9e4e56624246f389ff589989f258ba
=> [Internal Manager] Fetch balances on chain for tokens from balancer tokenlists

packages/next-app/src/app/stableswapsimulator/(components)/GraphView.tsx
This PR solves the build error on NextJS with plotly
=> [Stable Swap] Add dynamic import without SSR on Charts

packages/next-app/src/components/Plot.tsx
=> [Stableswap Simulator] add generic Plot component with default layout and config

packages/next-app/src/app/stableswapsimulator/(components)/GraphView.tsx, packages/next-app/src/app/stableswapsimulator/(components)/Menu.tsx, packages/next-app/src/app/stableswapsimulator/(components)/StableCurve.tsx, packages/next-app/src/app/stableswapsimulator/layout.tsx, packages/next-app/src/components/Plot.tsx, packages/next-app/src/components/Tabs.tsx
This PR adds:
- Generic Tabs;
- Tabs on chart;
- use generic plot on swap curve;
- Variant data on chart;
- Fix hover text on first rendering.
https://www.loom.com/share/8aebe4a3d1a24210b920818d716ff964
=> [Stable Swap] Swap curve for Variant Dynamic Data

packages/next-app/src/app/stableswapsimulator/page.tsx
This PR adds an UI effect at pool data importation
=> Add imported data UI before going to next step

packages/next-app/src/app/stableswapsimulator/(components)/DepthCost.tsx, packages/next-app/src/app/stableswapsimulator/(components)/GraphView.tsx, packages/next-app/src/app/stableswapsimulator/(components)/ImpactCurve.tsx, packages/next-app/src/app/stableswapsimulator/(components)/StableCurve.tsx, packages/next-app/src/components/Plot.tsx
This PR Adds:
- Tooltip to Charts
https://www.loom.com/share/5bacd13ecde4470b93806cf84339331b
=> Add tooltips to plots

packages/next-app/src/app/stableswapsimulator/analysis/page.tsx, packages/next-app/src/app/stableswapsimulator/layout.tsx, packages/next-app/src/app/stableswapsimulator/page.tsx
https://www.loom.com/share/70b8e3c606f241ae8960e8e69e952698
=> [Stable Swap] Improve Charts Page Y Overflow

packages/next-app/src/app/internalmanager/(components)/TokenSelect.tsx, packages/next-app/src/app/internalmanager/[network]/[operationKind]/page.tsx, packages/next-app/src/app/internalmanager/[network]/[operationKind]/token/[tokenAddress]/page.tsx, packages/next-app/src/components/Table.tsx, packages/next-app/src/components/TransactionProgressBar.tsx, packages/next-app/src/hooks/useTransaction.ts, packages/shared/index.ts
This PR fix:
- add a hover to the token row like on Balancer app;
- Disable the button / add a spinner after user approves, deposits, etc;
- this address shouldn't have worked 0xDA5Db233A6CfBB66dd5394D87d017EB69662737f11111340
=> [Internal Manager] batch of fixes and improvements

packages/next-app/src/app/internalmanager/(components)/BatchWithdraeButton.tsx, packages/next-app/src/app/internalmanager/(components)/TokenTable.tsx, packages/next-app/src/app/internalmanager/[network]/page.tsx
This PR solves [this issue](https://linear.app/bleu-llc/issue/BAL-473/balancer-tools-network-handling-is-breaking)
=> [Internal Manager] Remove gql query from homepage

packages/next-app/src/app/internalmanager/[network]/[operationKind]/token/[tokenAddress]/page.tsx, packages/next-app/src/components/TransactionProgressBar.tsx, packages/next-app/src/contexts/InternalManagerContext.tsx, packages/next-app/src/hooks/useTransaction.ts
https://linear.app/bleu-llc/issue/BAL-493/check-allowance-before-asking-to-approve
https://www.loom.com/share/f93700ad3e154948ab9698add5102cb7?sid=f6590b42-25d4-49fe-9010-1b9e209ed4e7
Todo:
=> [Internal Manager] Check allowance before asking to approve

packages/next-app/src/app/internalmanager/[network]/[operationKind]/token/[tokenAddress]/page.tsx, packages/next-app/src/contexts/InternalManagerContext.tsx, packages/next-app/src/hooks/useTransaction.ts
On https://github.com/bleu-studio/balancer-tools/pull/153 I added an extra step and after some testing on production the behavior was not the expected one
=> [Internal Manager] Remove extra step

packages/next-app/package.json, packages/next-app/src/app/internalmanager/(components)/TokenSelect.tsx, packages/next-app/src/hooks/internalmanager/useTokenApproval.ts, packages/next-app/src/wagmi/writeTokenApproval.ts, pnpm-lock.yaml
This PR changes:
- approve token default value to MaxUint256
- token icon on TokenSelect to 22px
Token Icon:
approve default value:
=> [Internal Manager] approve default value to MaxUint256 and change token icon size

apps/balancer-tools/package.json, apps/balancer-tools/src/__tests__/components/Button.test.tsx, apps/balancer-tools/src/components/Button.tsx
This PR adds `test` script on` balancer-tools` next app and adds a test for the `Button.tsx` component
=> [Maintenance] Add Button test

apps/balancer-tools/src/__tests__/components/Button.test.tsx, apps/balancer-tools/src/app/metadata/[network]/pool/[poolId]/pin/route.ts, apps/balancer-tools/src/app/poolsimulator/(components)/Menu.tsx, apps/balancer-tools/src/app/poolsimulator/(components)/PoolParamsForm.tsx, apps/balancer-tools/src/app/poolsimulator/(components)/SearchPoolFormDialog.tsx, apps/balancer-tools/src/app/poolsimulator/(components)/TokenTable.tsx, apps/balancer-tools/src/app/poolsimulator/(types)/index.ts, apps/balancer-tools/src/app/poolsimulator/(utils)/index.ts, apps/balancer-tools/src/components/Button.tsx, apps/balancer-tools/src/components/SearchPoolForm.tsx, apps/balancer-tools/src/components/Tabs.tsx, apps/balancer-tools/src/contexts/PoolSimulatorContext.tsx, apps/balancer-tools/src/lib/schema.ts, package.json, packages/gql/src/balancer/pools.ts, pnpm-lock.yaml
This PR adds:
- Gyro 2 and 3 Forms;
- Gyro 2 and 3 schema validation;
- get sqrtAlpha sqrtBeta root3Alpha from subgraph
- on SearchPoolForm show a message when there is no pool under that network
https://www.loom.com/share/9c77bb0b49fc4fa8af95a8c922df379b?sid=110ebdf9-537e-43be-817d-fc86619c0b71
=> [Pool Simulator] Implement gyro 2 and 3 forms

apps/balancer-tools/src/app/poolsimulator/(components)/DepthCost.tsx, apps/balancer-tools/src/app/poolsimulator/(components)/ImpactCurve.tsx, apps/balancer-tools/src/app/poolsimulator/(components)/SwapCurve.tsx, apps/balancer-tools/src/app/poolsimulator/(components)/SwapSimulator.tsx, apps/balancer-tools/src/app/poolsimulator/(types)/index.ts, apps/balancer-tools/src/app/poolsimulator/(utils)/index.ts, apps/balancer-tools/src/app/poolsimulator/analysis/page.tsx, apps/balancer-tools/src/contexts/PoolSimulatorContext.tsx, apps/balancer-tools/src/contexts/networks.tsx, apps/balancer-tools/src/lib/schema.ts, packages/math-poolsimulator/src/gyro2/fixtures/data.json, packages/math-poolsimulator/src/gyro2/index.test.ts, packages/math-poolsimulator/src/gyro2/index.ts, packages/math-poolsimulator/src/types.ts
This PR adds the Gyro 2CLP math interface
=> [Pool Simulator] Implement gyro 2CLP math

apps/balancer-tools/src/app/poolsimulator/(components)/ImpactCurve.tsx, apps/balancer-tools/src/app/poolsimulator/(components)/SwapCurve.tsx
https://www.loom.com/share/bc97b64979e44387a9f43182972ef656?sid=aa387335-9aa0-451a-98d8-8982d18ef5d0
Also, rename `variant` to `custom` identification on Price Impact Curve
=> [Pool Simulator] Add points as pool limit in both curves

README.md, apps/balancer-tools/src/app/poolsimulator/(components)/AnalysisPage.tsx, apps/balancer-tools/src/app/poolsimulator/(components)/Menu.tsx, apps/balancer-tools/src/app/poolsimulator/(components)/SwapCurve.tsx, apps/balancer-tools/src/app/poolsimulator/(utils)/index.ts, apps/balancer-tools/src/contexts/PoolSimulatorContext.tsx, packages/math-poolsimulator/src/fx/fixtures/data.json, packages/math-poolsimulator/src/fx/index.test.ts, packages/math-poolsimulator/src/fx/index.ts, packages/math-poolsimulator/src/types.ts
=> update repo README

apps/balancer-tools/src/app/poolsimulator/(components)/AnalysisPage.tsx, apps/balancer-tools/src/app/poolsimulator/(components)/ImpactCurve.tsx, apps/balancer-tools/src/app/poolsimulator/(components)/SwapCurve.tsx, apps/balancer-tools/src/app/poolsimulator/(workers)/impact-curve-calculation.ts, apps/balancer-tools/src/app/poolsimulator/(workers)/swap-curve-calculation.ts, apps/balancer-tools/src/contexts/PoolSimulatorContext.tsx
This PR:
- Add `swap-curve-calculation.ts` and it's use on `SwapCurve`
- Add `impact-curve-calculation.ts` and it's use on `ImpactCurve`
- remove Spinners from the analysis page
https://www.loom.com/share/490f64ccec6d4b4aa11da8c096901806?sid=5b1de0d5-9e1f-4996-816b-3185307921f9
=> [Pool Simulator] Add web workers for swap and impact curve

apps/balancer-tools/src/app/poolsimulator/(components)/PoolParamsForm.tsx, apps/balancer-tools/src/components/Input.tsx
This PR solves the Balancer Feedback about the second milestone by adding tooltips and links to the documentation
https://www.loom.com/share/ce5a7fbf65d646479ca00110f344e6bf
=> Add tooltips and documentation links

apps/balancer-tools/src/app/apr/round/(components)/PoolsCards.tsx, apps/balancer-tools/src/app/apr/round/(components)/TopPoolsChart.tsx, apps/balancer-tools/src/app/apr/round/[roundId]/page.tsx
Added chart for top pools, I'm kinda stuck on how are we going to share the pool data without refetch at every component that needs it. I think the simpler answer is just to have a parent component hold all that data and just pass it as prop, however I'd like to know how you guys would go about it.
Also, I found that visualing customizing Plotly is very annoying and require some workarounds (eg: [Making the bars end round](https://gist.github.com/mebaysan/80d6c3974d7700b8e6f3a8dca8ccdd03))
=> [APR] top apr pools chart

apps/balancer-tools/src/app/poolsimulator/(components)/ShareButton.tsx, apps/balancer-tools/src/app/poolsimulator/layout.tsx, apps/balancer-tools/src/components/Header.tsx, apps/balancer-tools/src/contexts/PoolSimulatorContext.tsx
=> [Pool Simulator] Fix share simulation feature

apps/balancer-tools/package.json, apps/balancer-tools/src/app/apr/(utils)/sortChartData.ts, apps/balancer-tools/src/app/apr/round/(components)/PoolListTable.tsx, pnpm-lock.yaml
Initial Implementation of Request Throttling.
In the first version of the request throttling mechanism, I've designed an instanced a Throttle within each component. This approach enables each component to have its own distinct throttle configurations. An alternative approach would involve creating the throttle instance at the page level and then passing it to the components as a prop. This second approach would centralize request throttling for all the requests originating from that particular page.
Here's in action with really batches of 3 and interval of 5s:
https://github.com/bleu-studio/balancer-tools/assets/68453900/07abc877-e465-4eb3-a6e4-1953d602b1a5
=> [APR] p-throttle implementation

apps/balancer-tools/src/app/poolsimulator/(components)/Curves/ImpactCurve.tsx, apps/balancer-tools/src/app/poolsimulator/(components)/Curves/SwapCurve.tsx, apps/balancer-tools/src/app/poolsimulator/(components)/Curves/getBetaLimits.test.ts, apps/balancer-tools/src/app/poolsimulator/(components)/Curves/getBetaLimits.ts
=> [Pool Simulator] Use price rate on beta region calculations

apps/balancer-tools/src/app/apr/(utils)/calculatePoolStats.ts, apps/balancer-tools/src/app/apr/(utils)/getRelativeWeight.ts, apps/balancer-tools/src/app/apr/api/route.ts, apps/balancer-tools/src/app/apr/pool/(components)/HistoricalAPRChart.tsx, apps/balancer-tools/src/app/apr/pool/(components)/HistoricalAPRPlot.tsx, apps/balancer-tools/src/app/apr/round/(components)/PoolListTable.tsx, apps/balancer-tools/src/app/apr/round/(components)/RoundOverviewCards.tsx, apps/balancer-tools/src/lib/balancer/gauges.ts
TODO: Typing and formatting cc @luizakp
=> [APR] API bugfixes

apps/balancer-tools/src/app/apr/(components)/HeaderEndButton.tsx, apps/balancer-tools/src/app/apr/layout.tsx, apps/balancer-tools/src/app/apr/pool/[network]/[poolId]/page.tsx, apps/balancer-tools/src/app/apr/pool/[network]/[poolId]/round/[roundId]/page.tsx, apps/balancer-tools/src/app/apr/round/[roundId]/page.tsx, apps/balancer-tools/src/app/apr/round/page.tsx, apps/balancer-tools/src/components/SearchPoolForm/index.tsx, apps/balancer-tools/src/components/Select.tsx
[rawallon/bal-709-redo-interface](https://github.com/bleu-studio/balancer-tools/assets/68453900/84bff54b-00a9-4b75-bf1c-b28cfa505ac8)
=> [APR] Move sidebar to header

apps/balancer-tools/next.config.js, apps/balancer-tools/src/app/apr/(utils)/calculatePoolStats.ts, apps/balancer-tools/src/app/apr/(utils)/getBALPriceByRound.ts, apps/balancer-tools/src/app/apr/api/route.ts, apps/balancer-tools/src/app/apr/pool/(components)/PoolTokens.tsx, apps/balancer-tools/src/app/apr/pool/(components)/PoolTokensTable.tsx, apps/balancer-tools/src/app/apr/pool/[network]/[poolId]/page.tsx, apps/balancer-tools/src/app/apr/pool/[network]/[poolId]/round/[roundId]/page.tsx, apps/balancer-tools/src/components/Table.tsx, apps/balancer-tools/src/lib/balancer/gauges.ts, packages/gql/src/balancer/__generated__/Arbitrum.server.ts, packages/gql/src/balancer/__generated__/Arbitrum.ts, packages/gql/src/balancer/__generated__/Ethereum.server.ts, packages/gql/src/balancer/__generated__/Ethereum.ts, packages/gql/src/balancer/__generated__/Gnosis.server.ts, packages/gql/src/balancer/__generated__/Gnosis.ts, packages/gql/src/balancer/__generated__/Goerli.server.ts, packages/gql/src/balancer/__generated__/Goerli.ts, packages/gql/src/balancer/__generated__/Optimism.server.ts, packages/gql/src/balancer/__generated__/Optimism.ts, packages/gql/src/balancer/__generated__/Polygon-zkevm.server.ts, packages/gql/src/balancer/__generated__/Polygon-zkevm.ts, packages/gql/src/balancer/__generated__/Polygon.server.ts, packages/gql/src/balancer/__generated__/Polygon.ts, packages/gql/src/balancer/__generated__/Sepolia.server.ts, packages/gql/src/balancer/__generated__/Sepolia.ts, packages/gql/src/balancer/pools.ts
[Deployed](https://tools-monorepo-jbi2533os-ribeirojose.vercel.app/apr/pool/ethereum/0x6f0ed6f346007563d3266de350d174a831bde0ca0001000000000000000005db/round/74)
<details><summary>Balancer's</summary>
</details>
When the pools is not weighted it doesnt show the "Volume" col
=> [APR] Tokens on pool page

apps/balancer-tools/src/app/apr/(components)/KPI.tsx, apps/balancer-tools/src/app/apr/(components)/MultiSelectDropdown.tsx, apps/balancer-tools/src/app/apr/(components)/OverviewCards.tsx, apps/balancer-tools/src/app/apr/layout.tsx, apps/balancer-tools/src/app/apr/pool/(components)/HistoricalAPRPlot.tsx, apps/balancer-tools/src/app/apr/pool/(components)/PoolTokensTable.tsx, apps/balancer-tools/src/app/apr/round/(components)/Breadcrumb.tsx, apps/balancer-tools/src/app/apr/round/(components)/MoreFiltersButton.tsx, apps/balancer-tools/src/app/apr/round/(components)/PoolListTable.tsx, apps/balancer-tools/src/app/daoadmin/layout.tsx, apps/balancer-tools/src/app/internalmanager/layout.tsx, apps/balancer-tools/src/app/layout.tsx, apps/balancer-tools/src/app/metadata/layout.tsx, apps/balancer-tools/src/app/poolsimulator/layout.tsx, apps/balancer-tools/src/components/Badge.tsx, apps/balancer-tools/src/components/Header.tsx, apps/balancer-tools/src/components/Plot.tsx, apps/balancer-tools/src/components/Table.tsx, apps/balancer-tools/src/components/TooltipMobile.tsx
https://github.com/bleu-studio/balancer-tools/assets/68453900/0296bd4f-ec72-4d74-960d-bd5a51d4cc6c
=> [APR] Mobile design revamp

apps/balancer-tools/.gitignore, apps/balancer-tools/package.json, apps/balancer-tools/src/app/apr/(utils)/calculatePoolStats.ts, apps/balancer-tools/src/app/apr/api/route.ts, apps/balancer-tools/src/components/Header.tsx, apps/balancer-tools/src/data/voting-gauges.json, apps/balancer-tools/src/lib/cache.ts, apps/pool-metadata/contracts/package.json, apps/pool-metadata/subgraph/package.json, package.json, packages/eslint-config/package.json, packages/gql/package.json, packages/math-poolsimulator/package.json, packages/tsconfig/package.json, packages/utils/package.json, pnpm-lock.yaml
You'll need to pull the remove KV credentials when developing locally: `vercel env pull .env.development.local`
=> use KV cache

apps/balancer-tools/src/app/apr/pool/(components)/HistoricalCharts/HistoricalData/formatAPRChartData.tsx
=> [APR] Add TokenAPR to historical chart

apps/balancer-tools/src/app/apr/(utils)/calculatePoolStats.ts, apps/balancer-tools/src/app/apr/api/route.ts
This PR changes the API from roundId to startAt/endAt, however it isn't deployable alone, the UI also needs to be changed to the [new return format](https://www.notion.so/API-Documentation-f0732e25a1814b16aade0a41e3febc30), example of returns on the comments.
=> [APR] Refactor unity of aggregation to be day

apps/balancer-tools/src/app/apr/(utils)/calculatePoolStats.ts, apps/balancer-tools/src/app/apr/api/(utils)/computeAverages.ts, apps/balancer-tools/src/app/apr/api/(utils)/date.ts, apps/balancer-tools/src/app/apr/api/(utils)/fetchDataForPoolId.ts, apps/balancer-tools/src/app/apr/api/(utils)/fetchDataForPoolIdDateRange.ts, apps/balancer-tools/src/app/apr/api/(utils)/fetchForDateRange.ts, apps/balancer-tools/src/app/apr/api/(utils)/filter.ts, apps/balancer-tools/src/app/apr/api/(utils)/sort.ts, apps/balancer-tools/src/app/apr/api/(utils)/validate.ts, apps/balancer-tools/src/app/apr/api/route.ts
- attempting to make things a bit easier to parse while I was reviewing the code;
- prefer to using zod so that we can centralize validation logic and give helpful error messages. also helps with typing.;
=> refactor apr api into multiple files, use zod

apps/balancer-tools/src/app/poolsimulator/(components)/Curves/ImpactCurve.tsx, apps/balancer-tools/src/app/poolsimulator/(components)/Curves/SwapCurve.tsx
=> [Pool Simulator] Fix wrong color on extra custom information

apps/balancer-tools/src/app/apr/(utils)/getFilteredApiUrl.ts, apps/balancer-tools/src/app/apr/api/(utils)/computeAverages.ts, apps/balancer-tools/src/app/apr/page.tsx, apps/balancer-tools/src/app/apr/pool/(components)/HistoricalCharts/index.tsx, apps/balancer-tools/src/app/apr/pool/(components)/PoolOverviewCards.tsx, apps/balancer-tools/src/app/apr/round/(components)/PoolListTable.tsx
Changes hard-coded URL in favor of using a function that generates the URL with search params
=> [APR] use getfilterdatafromparams when making a request

apps/balancer-tools/src/app/poolsimulator/(components)/Curves/ImpactCurve.tsx, apps/balancer-tools/src/app/poolsimulator/(utils)/getBetaLimits.ts, apps/balancer-tools/src/app/poolsimulator/(workers)/impact-curve-calculation.ts
The beta limit wasn't recalculated if some parameter changed. Inside the worker it updates.
=> [Pool Simulator] fix: move beta limit calculation to worker

apps/balancer-tools/src/app/apr/(components)/ErrorTemplate.tsx, apps/balancer-tools/src/app/apr/(utils)/calculatePoolStats.ts, apps/balancer-tools/src/app/apr/api/(utils)/fetchDataForPoolIdDateRange.ts, apps/balancer-tools/src/app/apr/api/route.ts, apps/balancer-tools/src/app/apr/not-found.tsx, apps/balancer-tools/src/app/apr/pool/(components)/PoolOverviewCards.tsx, apps/balancer-tools/src/app/apr/pool/[network]/[poolId]/error/page.tsx, apps/balancer-tools/src/app/apr/pool/[network]/[poolId]/page.tsx
https://www.loom.com/share/94a8ae2d62524319a2c9125e3a618caa?sid=46906aee-ffa9-46f9-ac2f-ea8e79f5a9c4
=> [APR] Handle when selected date is lower than pool created date

apps/balancer-tools/src/app/apr/(utils)/calculateApr.ts, apps/balancer-tools/src/app/apr/(utils)/calculatePoolStats.ts, apps/balancer-tools/src/app/apr/api/(utils)/date.ts, apps/balancer-tools/src/app/apr/page.tsx, apps/balancer-tools/src/app/apr/pool/[network]/[poolId]/page.tsx, apps/balancer-tools/src/lib/balancer/emissions.ts
This PR separates APR async calls from calculate pool stats
=> [APR] Refactor apr calculation

apps/balancer-tools/src/app/apr/(utils)/calculateApr.ts, apps/balancer-tools/src/app/apr/(utils)/calculatePoolStats.ts, apps/balancer-tools/src/app/apr/(utils)/tokenApr.ts, apps/balancer-tools/src/app/apr/(utils)/vunerabilityAffectedPool.ts, apps/balancer-tools/src/app/apr/api/route.ts, apps/balancer-tools/src/app/apr/layout.tsx, apps/balancer-tools/src/utils/fetcher.ts
This PR:
- add more bb pools
- increase the maxDuration of the server function
- Add missing suspense on header
=> [APR] Investigating Prod bugs pt.1

apps/balancer-tools/src/app/apr/(utils)/tokenApr.ts, apps/balancer-tools/src/app/apr/(utils)/vunerabilityAffectedPool.ts
This PR:
- Fix syntaxerror unexpected token in json at position 0
- add bb pools
=> [APR] Fix: end block one day ahead

apps/balancer-tools/src/app/apr/(components)/Breadcrumb.tsx, apps/balancer-tools/src/app/apr/(components)/HomeOverviewCards.tsx, apps/balancer-tools/src/app/apr/(components)/MoreFiltersButton.tsx, apps/balancer-tools/src/app/apr/(components)/PoolListTable.tsx, apps/balancer-tools/src/app/apr/(components)/PoolTableWrapper.tsx, apps/balancer-tools/src/app/apr/(components)/TokenFilterInput.tsx, apps/balancer-tools/src/app/apr/(components)/TopPoolsChart.tsx, apps/balancer-tools/src/app/apr/(components)/TopPoolsChartWrapper.tsx, apps/balancer-tools/src/app/apr/(utils)/getFilteredApiUrl.ts, apps/balancer-tools/src/app/apr/page.tsx, apps/balancer-tools/src/app/apr/pool/[network]/[poolId]/page.tsx, apps/balancer-tools/src/app/apr/round/page.tsx
This PR:
- fix go to pool
- delete `round` route and move components to apr root components folder
=> [APR] fix go to pool

apps/balancer-tools/package.json, apps/balancer-tools/src/components/Fathom.tsx, apps/balancer-tools/src/components/RootLayout.tsx, pnpm-lock.yaml
This PR followed the new docs for next 13 https://github.com/derrickreimer/fathom-client#nextjs
=> [APR] Add fathom to balancer toolsbleufi

packages/gql/src/balancer/__generated__/Arbitrum.server.ts, packages/gql/src/balancer/__generated__/Arbitrum.ts, packages/gql/src/balancer/__generated__/Avalanche.server.ts, packages/gql/src/balancer/__generated__/Avalanche.ts, packages/gql/src/balancer/__generated__/Base.server.ts, packages/gql/src/balancer/__generated__/Base.ts, packages/gql/src/balancer/__generated__/Ethereum.server.ts, packages/gql/src/balancer/__generated__/Ethereum.ts, packages/gql/src/balancer/__generated__/Gnosis.server.ts, packages/gql/src/balancer/__generated__/Gnosis.ts, packages/gql/src/balancer/__generated__/Goerli.server.ts, packages/gql/src/balancer/__generated__/Goerli.ts, packages/gql/src/balancer/__generated__/Optimism.server.ts, packages/gql/src/balancer/__generated__/Optimism.ts, packages/gql/src/balancer/__generated__/Polygon-zkevm.server.ts, packages/gql/src/balancer/__generated__/Polygon-zkevm.ts, packages/gql/src/balancer/__generated__/Polygon.server.ts, packages/gql/src/balancer/__generated__/Polygon.ts, packages/gql/src/balancer/__generated__/Sepolia.server.ts, packages/gql/src/balancer/__generated__/Sepolia.ts, packages/gql/src/balancer/pools.ts
closes [BAL-1160](https://linear.app/bleu-llc/issue/BAL-1160/fix-token-filter)
=> [APR] APR Pools query with tokens

apps/balancer-tools/src/app/apr/api/(utils)/fetchForDateRange.ts, packages/gql/src/balancer/__generated__/Arbitrum.server.ts, packages/gql/src/balancer/__generated__/Arbitrum.ts, packages/gql/src/balancer/__generated__/Avalanche.server.ts, packages/gql/src/balancer/__generated__/Avalanche.ts, packages/gql/src/balancer/__generated__/Base.server.ts, packages/gql/src/balancer/__generated__/Base.ts, packages/gql/src/balancer/__generated__/Ethereum.server.ts, packages/gql/src/balancer/__generated__/Ethereum.ts, packages/gql/src/balancer/__generated__/Gnosis.server.ts, packages/gql/src/balancer/__generated__/Gnosis.ts, packages/gql/src/balancer/__generated__/Goerli.server.ts, packages/gql/src/balancer/__generated__/Goerli.ts, packages/gql/src/balancer/__generated__/Optimism.server.ts, packages/gql/src/balancer/__generated__/Optimism.ts, packages/gql/src/balancer/__generated__/Polygon-zkevm.server.ts, packages/gql/src/balancer/__generated__/Polygon-zkevm.ts, packages/gql/src/balancer/__generated__/Polygon.server.ts, packages/gql/src/balancer/__generated__/Polygon.ts, packages/gql/src/balancer/__generated__/Sepolia.server.ts, packages/gql/src/balancer/__generated__/Sepolia.ts, packages/gql/src/balancer/pools.ts
When tokenList = [] return the APR Pools as no token is selected
=> [APR] Fix apr pools

apps/balancer-tools/src/app/apr/(components)/PoolListTable.tsx, apps/balancer-tools/src/app/apr/(utils)/calculatePoolStats.ts, apps/balancer-tools/src/app/apr/api/route.ts, apps/balancer-tools/src/app/apr/page.tsx, apps/balancer-tools/src/app/apr/pool/[network]/[poolId]/page.tsx, apps/balancer-tools/src/components/Tooltip.tsx
https://www.loom.com/share/16309269f9a341b3830c7bed14dca1c6?sid=541a19d4-bf14-460f-aed2-e21d2ef1f16c
This PR:
- changes the default date range for yesterday;
- add hover on apr on pool list
- revalidate page once per day
=> [APR] Add page revalidate

apps/cow-tools/src/app/milkman/[network]/HomePageWrapper.tsx, apps/cow-tools/src/app/milkman/[network]/order/new/page.tsx, apps/cow-tools/src/lib/priceCheckers.ts
https://www.loom.com/share/9d94582c22aa400fbc00936b5cdb4ae0?sid=a0ae2252-9dc7-4ced-8b57-c64938c27f43
CLOSES [BLEU-377](https://linear.app/bleu-llc/issue/BLEU-377/add-uni-v2-price-checker-pt-2)
=> [Milkmapp] Trigger real orders for Uni v2 and Fixed min out price checkers

apps/cow-tools/src/app/milkman/[network]/order/new/page.tsx, apps/cow-tools/src/lib/priceCheckers.ts
https://www.loom.com/share/ea5329332c6346f49bf46bc6a0f96495
=> [MilkmApp] Add sushiswap price checker

apps/cow-tools/src/app/milkman/(components)/TokenSelect.tsx, apps/cow-tools/src/app/milkman/[network]/order/new/page.tsx, apps/cow-tools/src/components/Dialog.tsx, apps/cow-tools/src/hooks/useSafeBalances.ts, apps/cow-tools/src/lib/priceCheckers.ts
- Add token select with available balance
- Selected tokens are registered to forms
https://www.loom.com/share/cf3c449dbe18488b8bc640c7b573f9c9?sid=7f22ed97-eba9-4bfc-9c5d-763650f843a3
=> [Milkman] Token search modal w/o cow token list

apps/cow-tools/src/app/milkman/(components)/TokenSelect.tsx, apps/cow-tools/src/app/milkman/[network]/order/new/page.tsx, apps/cow-tools/src/lib/priceCheckers.ts, apps/cow-tools/src/lib/schema.ts, pnpm-lock.yaml
https://www.loom.com/share/aa790d3a176948a3abd840cbf3d19bd2
=> Add new order form validations pt 1

apps/balancer-tools/seed.ts, apps/balancer-tools/src/app/apr/(utils)/calculateApr.ts, apps/balancer-tools/src/app/apr/(utils)/calculatePoolStats.ts, apps/balancer-tools/src/app/apr/(utils)/getRelativeWeight.ts, apps/balancer-tools/src/app/apr/api/(utils)/fetchDataForPoolIdDateRange.ts, apps/balancer-tools/src/app/apr/api/(utils)/fetchForDateRange.ts, apps/balancer-tools/src/db/migrations/0000_charming_victor_mancha.sql, apps/balancer-tools/src/db/migrations/0000_wise_justice.sql, apps/balancer-tools/src/db/migrations/meta/0000_snapshot.json, apps/balancer-tools/src/db/migrations/meta/_journal.json, apps/balancer-tools/src/db/schema.ts
- create rounds table
- create emissions table
- populate gaugeSnapshot
- calculate veBAL APR
=> [APR] veBAL APR on DB

apps/cow-tools/src/app/milkman/(components)/SingleOrderForm/Footer.tsx, apps/cow-tools/src/app/milkman/(components)/SingleOrderForm/PriceChecker.tsx, apps/cow-tools/src/app/milkman/(components)/SingleOrderForm/Summary.tsx, apps/cow-tools/src/app/milkman/(components)/TransactionCard.tsx
https://www.loom.com/share/6287496f468543b7bba4559dd2ba7f0b
=> [MilkmApp] Add multiple orders form

apps/balancer-tools/src/app/apr/(components)/HomeOverviewCards.tsx, apps/balancer-tools/src/app/apr/(components)/MoreFiltersButton.tsx, apps/balancer-tools/src/app/apr/(components)/PoolListTable.tsx, apps/balancer-tools/src/app/apr/(components)/PoolListTableWrapper.tsx, apps/balancer-tools/src/app/apr/(components)/TopPoolsChartWrapper.tsx, apps/balancer-tools/src/app/apr/(utils)/fetchDataTypes.ts, apps/balancer-tools/src/app/apr/(utils)/fetchForDateRange.ts, apps/balancer-tools/src/app/apr/(utils)/types.ts, apps/balancer-tools/src/app/apr/(utils)/validate.ts, apps/balancer-tools/src/app/apr/page.tsx
https://www.loom.com/share/dac98b32cef0468681803b5f29540d89?sid=db762227-02e6-4e65-8a0c-328057caa44c
=> [APR] refactor pool table sort and filtering using db

apps/balancer-tools/src/app/apr/(components)/MoreFiltersButton.tsx, apps/balancer-tools/src/app/apr/(components)/PoolListTable.tsx, packages/balancer-apr/src/index.ts
This PR adds:
- load more button
- remove timeout fore more filters
- fix vebal rounds seed
=> [APR] Add button to load more pools

apps/cow-tools/src/app/milkman/(components)/OrderTable/CancelButton.tsx, apps/cow-tools/src/app/milkman/(components)/OrderTable/TableRowTransaction.tsx, apps/cow-tools/src/app/milkman/(components)/SingleOrderForm/PriceChecker.tsx, apps/cow-tools/src/app/milkman/(components)/SingleOrderForm/Summary.tsx, apps/cow-tools/src/app/milkman/(components)/SingleOrderForm/Twap.tsx, apps/cow-tools/src/app/milkman/(components)/TokenSelect.tsx, apps/cow-tools/src/app/milkman/[network]/HomePageWrapper.tsx, apps/cow-tools/src/app/milkman/[network]/order/new/page.tsx, apps/cow-tools/src/app/milkman/utils/type.ts, apps/cow-tools/src/components/ProgressBar.tsx, apps/cow-tools/src/components/RootLayout.tsx, apps/cow-tools/src/components/Toast.tsx, apps/cow-tools/src/lib/fetchCowQuote.ts, apps/cow-tools/src/lib/schema.ts, apps/cow-tools/src/utils/cowTokenList.ts
=> [MilkmApp] CoW feedbacks pt 1

apps/cow-tools/src/app/milkman/(components)/OrderTable/TableRowOrder.tsx, apps/cow-tools/src/app/milkman/(components)/OrderTable/TableRowTransaction.tsx, apps/cow-tools/src/app/milkman/(components)/OrderTable/index.tsx, apps/cow-tools/src/app/milkman/(components)/SingleOrderForm/Overview.tsx, apps/cow-tools/src/app/milkman/(components)/SingleOrderForm/Summary.tsx, apps/cow-tools/src/app/milkman/utils/cowExplorer.ts, apps/cow-tools/src/hooks/useRawTxData.ts, apps/cow-tools/src/hooks/useUserMilkmanTransactions.ts
https://docs.google.com/spreadsheets/d/1pgBzxXu-BQ02vpHKgktKQQyDoccjI8zCIfQOB2SAiYM/edit#gid=0
=> [MilkmApp] CoW Team final feedbacks

apps/cow-amm-deployer/src/app/amms/(components)/CreateAmmForm.tsx, apps/cow-amm-deployer/src/app/amms/(components)/TokenSelect.tsx, apps/cow-amm-deployer/src/lib/schema.ts, apps/cow-amm-deployer/src/lib/transactionFactory.ts
=> [CoW Amm Deployer] Check if route exists or not

apps/cow-amm-deployer/src/components/HomeWrapper.tsx, apps/cow-amm-deployer/src/lib/fetchTokenUsdPrice.ts
Errors:
https://uploads.linear.app/4cb85de2-34b2-42ab-8b73-888f21225aaf/8cdac9b3-27ab-4eb5-8fb9-ca4fd4544c28/ec1040cf-3078-4811-ae01-fa9a3bbc638f
I couldn't solve the token logo 403 errors. If you guys know how to solve it it would be great 🤓
=> [CoW AMM Deployer] Solve UI errors on the console

apps/cow-amm-deployer/src/lib/schema.ts
https://discord.com/channels/869166959739170836/869170255266734103/1220038725220958319
=> [CoW AMM Deployer] Calculate cow quote amount in based on minTradedToken0 amount

apps/cow-amm-deployer/src/app/[userId]/amms/[id]/(components)/EditAMMForm.tsx, apps/cow-amm-deployer/src/app/[userId]/amms/[id]/(components)/PriceInformation.tsx, apps/cow-amm-deployer/src/app/[userId]/amms/[id]/deposit/page.tsx, apps/cow-amm-deployer/src/app/[userId]/amms/[id]/page.tsx, apps/cow-amm-deployer/src/app/[userId]/amms/page.tsx, apps/cow-amm-deployer/src/app/[userId]/new/(components)/CreateAMMForm.tsx, apps/cow-amm-deployer/src/app/[userId]/new/(components)/TokenAmountInput.tsx, apps/cow-amm-deployer/src/components/BalancerWeightedForm.tsx, apps/cow-amm-deployer/src/components/ChainlinkForm.tsx, apps/cow-amm-deployer/src/components/CustomOracleForm.tsx, apps/cow-amm-deployer/src/components/DepositForm.tsx, apps/cow-amm-deployer/src/components/PriceOracleForm.tsx, apps/cow-amm-deployer/src/components/SushiForm.tsx, apps/cow-amm-deployer/src/components/TokenInfo.tsx, apps/cow-amm-deployer/src/components/TxPendingAlertCard.tsx, apps/cow-amm-deployer/src/components/UniswapV2Form.tsx, apps/cow-amm-deployer/src/lib/decodePriceOracle.ts, apps/cow-amm-deployer/src/lib/fetchAmmData.ts, apps/cow-amm-deployer/src/lib/fetchHasAmmTxPending.ts, apps/cow-amm-deployer/src/lib/schema.ts, apps/cow-amm-deployer/src/lib/transactionFactory.ts, apps/cow-amm-deployer/src/lib/types.ts
=> Add tx pending alert when tx interacting with the cowamm
